<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="generator" content="Hugo 0.72.0" />

  <title>R Basics: piping in tidyverse &middot; Brian Jungmin Park</title>

  <meta name="description" content="" />

  

<meta itemprop="name" content="R Basics: piping in tidyverse">
<meta itemprop="description" content="Working in R, oftentimes I find myself creating intermediate variables that serve no purpose other than to exist as a middle man.">
<meta itemprop="datePublished" content="2020-06-16T00:00:00&#43;00:00" />
<meta itemprop="dateModified" content="2020-06-16T00:00:00&#43;00:00" />
<meta itemprop="wordCount" content="1065">
<meta itemprop="image" content="https://brianjmpark.github.io/images/picture.jpg"/>



<meta itemprop="keywords" content="r,tidyverse," />

<meta name="twitter:card" content="summary_large_image"/>
<meta name="twitter:image" content="https://brianjmpark.github.io/images/picture.jpg"/>

<meta name="twitter:title" content="R Basics: piping in tidyverse"/>
<meta name="twitter:description" content="Working in R, oftentimes I find myself creating intermediate variables that serve no purpose other than to exist as a middle man."/>


<meta property="og:title" content="R Basics: piping in tidyverse" />
<meta property="og:description" content="Working in R, oftentimes I find myself creating intermediate variables that serve no purpose other than to exist as a middle man." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://brianjmpark.github.io/post/r-basics-piping-in-tidy-verse/" />
<meta property="og:image" content="https://brianjmpark.github.io/images/picture.jpg"/>
<meta property="article:published_time" content="2020-06-16T00:00:00+00:00" />
<meta property="article:modified_time" content="2020-06-16T00:00:00+00:00" /><meta property="og:site_name" content="Brian Jungmin Park" />



  <link type="text/css"
        rel="stylesheet"
        href="/css/print.css"
        media="print">

  <link type="text/css"
        rel="stylesheet"
        href="/css/poole.css">

  <link type="text/css"
        rel="stylesheet"
        href="/css/hyde.css">

  
<style type="text/css">
  .sidebar {
    background-color: #dbc8ae;
  }

  .read-more-link a {
    border-color: #dbc8ae;
  }

  .pagination li a {
    color: #dbc8ae;
    border: 1px solid #dbc8ae;
  }

  .pagination li.active a {
    background-color: #dbc8ae;
  }

  .pagination li a:hover {
    background-color: #dbc8ae;
    opacity: 0.75;
  }

  footer a,
  .content a,
  .related-posts li a:hover {
    color: #dbc8ae;
  }
</style>



  

  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700&display=swap">

  <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css"
        integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk="
        crossorigin="anonymous" />

  <link rel="apple-touch-icon-precomposed"
        sizes="144x144"
        href="/apple-touch-icon-144-precomposed.png">

  <link rel="shortcut icon" href="/favicon.png">

  
  </head>
<body>
  <aside class="sidebar">
  <div class="container">
    <div class="sidebar-about">
      
        
        <div class="author-image">
          <img src="/images/picture.jpg" class="img-circle img-headshot center" alt="Profile Picture">
        </div>
        
      

      <h1>Brian Jungmin Park</h1>

      
      <p class="lead">A Computer Science &amp; Sports Blog</p>
      
    </div>

    <nav>
      <ul class="sidebar-nav">
        <li>
          <a href="https://brianjmpark.github.io">Home</a>
        </li>
        <li>
          <a href="/about/">About</a>
        </li><li>
          <a href="/contact/">Contact</a>
        </li><li>
          <a href="/posts/">Posts</a>
        </li><li>
          <a href="/categories/">Categories</a>
        </li><li>
          <a href="/tags/">Tags</a>
        </li>
      </ul>
    </nav>

    <section class="social-icons">
      
      <a href="https://linkedin.com/in/bjp" rel="me" title="LinkedIn" target="_blank">
        <i class="fab fa-linkedin" aria-hidden="true"></i>
      </a>
      
      <a href="https://github.com/brianjmpark/" rel="me" title="GitHub" target="_blank">
        <i class="fab fa-github" aria-hidden="true"></i>
      </a>
      
      <a href="https://twitter.com/brianjmpark2" rel="me" title="Twitter" target="_blank">
        <i class="fab fa-twitter" aria-hidden="true"></i>
      </a>
      
    </section>
  </div>
</aside>



    <script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML"></script>
    
    <script type="text/x-mathjax-config">
    MathJax.Hub.Config({
        tex2jax: {
            inlineMath: [ ['$','$'], ["\\(","\\)"] ],
            displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
            processEscapes: true,
            processEnvironments: true
        },
        // Center justify equations in code and markdown cells. Elsewhere
        // we use CSS to left justify single line equations in code cells.
        displayAlign: 'center',
        "HTML-CSS": {
            styles: {'.MathJax_Display': {"margin": 0}},
            linebreaks: { automatic: true }
        }
    });
    </script>
    


  <main class="content container">
  <div class="post">
  <h1>R Basics: piping in tidyverse</h1>

  <div class="post-date">
    <time datetime="2020-06-16T00:00:00Z">Jun 16, 2020</time> &middot; 5 min read
  </div>

  


<p>Working in R, oftentimes I find myself creating intermediate variables that serve no purpose other than to exist as a middle man. Consider this example:</p>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## ── Attaching packages ─────────────────────────────────────────────────────────────────────── tidyverse 1.3.0 ──</code></pre>
<pre><code>## ✓ ggplot2 3.3.1     ✓ purrr   0.3.4
## ✓ tibble  3.0.1     ✓ dplyr   1.0.0
## ✓ tidyr   1.1.0     ✓ stringr 1.4.0
## ✓ readr   1.3.1     ✓ forcats 0.5.0</code></pre>
<pre><code>## ── Conflicts ────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>data(mtcars)
str(mtcars)</code></pre>
<pre><code>## &#39;data.frame&#39;:    32 obs. of  11 variables:
##  $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
##  $ cyl : num  6 6 4 6 8 6 8 4 4 6 ...
##  $ disp: num  160 160 108 258 360 ...
##  $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...
##  $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
##  $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
##  $ qsec: num  16.5 17 18.6 19.4 17 ...
##  $ vs  : num  0 0 1 1 0 1 0 1 1 1 ...
##  $ am  : num  1 1 1 0 0 0 0 0 0 0 ...
##  $ gear: num  4 4 4 3 3 3 3 4 4 4 ...
##  $ carb: num  4 4 1 1 2 1 4 2 2 4 ...</code></pre>
<p>I've loaded a toy data set called mtcars (for R Documentation on this data set, see: <a href="https://stat.ethz.ch/R-manual/R-patched/library/datasets/html/mtcars.html" class="uri">https://stat.ethz.ch/R-manual/R-patched/library/datasets/html/mtcars.html</a>). Essentially, the data contains 11 numeric variables of automobile performance (which comprises the columns) of 32 car models (which comprises the rows).</p>
<p>Say I want to group the data frame by one of the columns, in this case &quot;hp&quot; which stands for horsepower. Doing this will re-organize the rows such that rows with common values for horsepower will be grouped consecutively together. I'm going to store the result of this transformation to a new variable called mtcars2.</p>
<pre class="r"><code>mtcars2 &lt;- group_by(mtcars, hp)
head(mtcars2, n = 20)</code></pre>
<pre><code>## # A tibble: 20 x 11
## # Groups:   hp [15]
##      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1  21       6 160     110  3.9   2.62  16.5     0     1     4     4
##  2  21       6 160     110  3.9   2.88  17.0     0     1     4     4
##  3  22.8     4 108      93  3.85  2.32  18.6     1     1     4     1
##  4  21.4     6 258     110  3.08  3.22  19.4     1     0     3     1
##  5  18.7     8 360     175  3.15  3.44  17.0     0     0     3     2
##  6  18.1     6 225     105  2.76  3.46  20.2     1     0     3     1
##  7  14.3     8 360     245  3.21  3.57  15.8     0     0     3     4
##  8  24.4     4 147.     62  3.69  3.19  20       1     0     4     2
##  9  22.8     4 141.     95  3.92  3.15  22.9     1     0     4     2
## 10  19.2     6 168.    123  3.92  3.44  18.3     1     0     4     4
## 11  17.8     6 168.    123  3.92  3.44  18.9     1     0     4     4
## 12  16.4     8 276.    180  3.07  4.07  17.4     0     0     3     3
## 13  17.3     8 276.    180  3.07  3.73  17.6     0     0     3     3
## 14  15.2     8 276.    180  3.07  3.78  18       0     0     3     3
## 15  10.4     8 472     205  2.93  5.25  18.0     0     0     3     4
## 16  10.4     8 460     215  3     5.42  17.8     0     0     3     4
## 17  14.7     8 440     230  3.23  5.34  17.4     0     0     3     4
## 18  32.4     4  78.7    66  4.08  2.2   19.5     1     1     4     1
## 19  30.4     4  75.7    52  4.93  1.62  18.5     1     1     4     2
## 20  33.9     4  71.1    65  4.22  1.84  19.9     1     1     4     1</code></pre>
<p>As you can see, the group_by function as aggregated the rows by horsepower.</p>
<p>Now I want to see what the mean mileage (miles per gallon, or mpg) is for each group of car models. Would cars, on average, that has 110 hp have higher or lower mileage than cars with, say, 180? To do this I use summarise function and store the new information in yet another new variable.</p>
<pre class="r"><code>mpg_by_hp &lt;- summarise(mtcars2, mean_mpg = mean(mpg, na.rm = TRUE))</code></pre>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre class="r"><code>head(mpg_by_hp) </code></pre>
<pre><code>## # A tibble: 6 x 2
##      hp mean_mpg
##   &lt;dbl&gt;    &lt;dbl&gt;
## 1    52     30.4
## 2    62     24.4
## 3    65     33.9
## 4    66     29.8
## 5    91     26  
## 6    93     22.8</code></pre>
<p>Indeed, in the hp = 110 group, the mean mileage is higher than in hp = 180 group, as we expected.</p>
<p>The only data frame I need to show that the above statement is true is the last variable we get, which is mpg_by_hp. However I have reached this step from our original data in two steps, resulting in an intermediate variable mtcars2 that does not give us any meaningful information. In order to bypass this and go straight to my answer from my original starting point, I can use pipes.</p>
<p>%&gt;% notation is used to 'pipe' commands together. This leads R to take the result from the command preceding the pipe and immediately execute the rest of the command, without storing unnecessary information. Let's say I want to do the same thing as before with an added step of filtering out any horsepower-grouped cars with less than 20.0 mpg. I can do this in one command as such, beginning from the original data set mtcars:</p>
<pre class="r"><code>mpg_by_hp &lt;- mtcars %&gt;%
    group_by(hp) %&gt;%
    summarise(mean_mpg = mean(mpg)) %&gt;%
    filter(mean_mpg &gt; 20.0)</code></pre>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre class="r"><code>mpg_by_hp</code></pre>
<pre><code>## # A tibble: 11 x 2
##       hp mean_mpg
##    &lt;dbl&gt;    &lt;dbl&gt;
##  1    52     30.4
##  2    62     24.4
##  3    65     33.9
##  4    66     29.8
##  5    91     26  
##  6    93     22.8
##  7    95     22.8
##  8    97     21.5
##  9   109     21.4
## 10   110     21.1
## 11   113     30.4</code></pre>
<p>I can read the above command out loud by substituting %&gt;% with &quot;and&quot; or &quot;then.&quot;</p>
<p>Using pipes contextualizes the kinds of data transformation we are performing instead of what's being transformed. Not only this, it makes code much easier to maintain and read, which alone proves it to be a valuable tool in R basics.</p>

</div>


  </main>

  <footer>
  <div>
    &copy; Brian Jungmin Park 2020

    &middot; <a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank">CC BY-SA 4.0</a>

    &middot; Build with <a href="https://gohugo.io/" target="_blank">Hugo</a> & <a href="https://themes.gohugo.io/soho/" target="_blank">Soho</a> theme
  </div>
</footer>


  <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/js/all.min.js"
          integrity="sha256-MAgcygDRahs+F/Nk5Vz387whB4kSK9NXlDN3w58LLq0="
          crossorigin="anonymous"></script>

  

  
</body>
</html>
